base:
  project: mlops_wine

data_remote:
  gdrive: data_remote/winequality.csv

data:
  raw: data/raw/winequality.csv
  processed:
    train: data/processed/train_winequality.csv
    test: data/processed/test_winequality.csv
    split_ratio: 0.3
    random_state: 42 # Controls the shuffling applied to the data before applying the split
    label: TARGET # label

models:
  ElasticNet:
    params:
      #alpha: 0.88
      #l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.9
      #alpha: 0.5
      #l1_ratio: 0.68

model_dir: saved_models

reports:
  metrics: reports/metrics.json
  params: reports/params.json
