stages:
  #get_data:
  #  cmd: python packages/regression_model/random_forest_regressor/src/data_manager.py
  #  deps:
  #    - packages/regression_model/random_forest_regressor/src/data_manager.py
  #    - packages/regression_model/random_forest_regressor/config/core.py
  #    - packages/regression_model/random_forest_regressor/data
  #  outs:
  #    - packages/regression_model/random_forest_regressor/data/winequality.csv 
  train:
    cmd: python packages/random_forest_regressor/model/src/train_pipeline.py
    deps: 
      - packages/random_forest_regressor/model/src/pipeline.py
      - packages/random_forest_regressor/model/src/train_pipeline.py
      - packages/random_forest_regressor/model/src/data_manager.py
      - packages/random_forest_regressor/model/config/core.py
      - packages/random_forest_regressor/model/config/config.yml
      - packages/random_forest_regressor/model/data/winequality.csv
  predict:
    cmd: python packages/random_forest_regressor/model/src/predict.py
    deps: 
      - packages/random_forest_regressor/model/src/data_manager.py
      - packages/random_forest_regressor/model/config/core.py
      - packages/random_forest_regressor/model/config/config.yml
      - packages/random_forest_regressor/model/artifacts
  