base:
  project: mlops_wine
  random_state: 42
  target_col: TARGET

data_source:
  raw: data/raw/winequality.csv

split_data:
  train: data/processed/train_winequality.csv
  test: data/processed/test_winequality.csv
  split_ratio: 0.3

models:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89
  
model_dir: saved_models

